name: edurider
description: "Edurider app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  
  flutter_otp_text_field: ^1.1.0+2



  
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  


dev_dependencies:
  
  flutter_native_splash: ^2.4.4
  

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/edurider_logo.png
  fullscreen: true

flutter_native_splash:
  image: assets/edurider_logo.png
  color: "#1e5461"
  android: true
  ios: true

  android_12:
    image: assets/edurider_logo.png
    icon_background_color: "#1e5461"
    
     # Adjust this value (1.5 means 150% of the original size)

  web: false
  fullscreen: true
  

  



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/edurider_logo.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  